# ASSIGNMENT : IRIS MULTI-CLASS CLASSIFICATION

###### Purpose :
To predict the species of flower .
###### Description :
The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).
###### Requirements :
1) Code must be in tf 2.0 .

2) Accuracy must be in between 95-97% .

3) Model shouldn't be Overfit (You can add drop out layer for this) .

### STEP 1 : Load all the necessary libraries 

In [22]:
import numpy as np
import pandas as pd

import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

print("TensorFlow version: {}".format(tf.__version__))

TensorFlow version: 2.1.0


### STEP 2 : Data Preparation
This step consists of multiple sub steps from data loading [download](https://github.com/ramsha275/PIAIC-Sir-Anees-Quarter-2/blob/master/Deep%20Learning/iris.csv),shuffling ,spliting in **Train** and **Test** sets to one-hot-enconding on labels . 


In [10]:
mnist = tf.keras.datasets.mnist

In [12]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [13]:
train_dataset_url =pd.read_csv ("iris.csv")

train_dataset_url.head()


# train_dataset_fp = tf.keras.utils.get_file(fname=os.path.basename(train_dataset_url),
#                                            origin=train_dataset_url)

# print("Local copy of the dataset file: {}".format(train_dataset_fp))

sepal.length  sepal.width  petal.length  petal.width Species
0           5.0          3.5           1.4          0.2  Setosa
1           4.0          3.0           1.4          0.2  Setosa
2           4.0          3.2           1.3          0.2  Setosa
3           4.0          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [14]:
train, test = train_test_split(train_dataset_url, test_size=0.2)
print(len(train), 'train examples')
# print(len(val), 'validation examples')
print(len(test), 'test examples')

120 train examples
30 test examples


### STEP 3 : Model Architecture 


###### Input : 4 
###### 1 hidden Layer : 8 nodes
###### Output : 3

In [15]:
import pandas
# load dataset
dataframe = pandas.read_csv("iris.csv", header=None)
dataset = dataframe.values
X = dataset[:,0:4]
Y = dataset[:,4]
print(dataframe)


                0            1             2            3          4
0    sepal.length  sepal.width  petal.length  petal.width    Species
1               5          3.5           1.4           .2     Setosa
2               4            3           1.4           .2     Setosa
3               4          3.2           1.3           .2     Setosa
4               4          3.1           1.5           .2     Setosa
..            ...          ...           ...          ...        ...
146             6            3           5.2          2.3  Virginica
147             6          2.5             5          1.9  Virginica
148             6            3           5.2            2  Virginica
149             6          3.4           5.4          2.3  Virginica
150             5            3           5.1          1.8  Virginica

[151 rows x 5 columns]


In [24]:
x_train.shape

(60000, 28, 28)

In [25]:
y_train.shape

(60000,)

In [26]:
x_test.shape

(10000, 28, 28)

In [27]:
y_test.shape

(10000,)

### STEP 4 : Compilation Step 

In [16]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [28]:
from sklearn.preprocessing import LabelEncoder
# encode class values as integers
le = LabelEncoder()
encoded_Y = le.fit_transform(y_train)
encoded_y_train = tf.keras.utils.to_categorical(encoded_Y)
encoded_Y = le.fit_transform(y_test)
encoded_y_test = tf.keras.utils.to_categorical(encoded_Y)

In [29]:
encoded_Y

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [30]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [31]:
encoded_y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [81]:
model.fit(x_train , encoded_y_train , epochs=20)

Train on 60000 samples
Epoch 1/20
60000/60000 [==============================] - 5s 84us/sample - loss: 0.2445 - accuracy: 0.9428
Epoch 2/20
60000/60000 [==============================] - 5s 84us/sample - loss: 0.2413 - accuracy: 0.9432
Epoch 3/20
60000/60000 [==============================] - 5s 85us/sample - loss: 0.2397 - accuracy: 0.9413
Epoch 4/20
60000/60000 [==============================] - 5s 84us/sample - loss: 0.2536 - accuracy: 0.9406
Epoch 5/20
60000/60000 [==============================] - 5s 85us/sample - loss: 0.2242 - accuracy: 0.9437
Epoch 6/20
60000/60000 [==============================] - 5s 84us/sample - loss: 0.2557 - accuracy: 0.9384
Epoch 7/20
60000/60000 [==============================] - 5s 86us/sample - loss: 0.2445 - accuracy: 0.9422
Epoch 8/20
60000/60000 [==============================] - 5s 87us/sample - loss: 0.2423 - accuracy: 0.9403
Epoch 9/20
60000/60000 [==============================] - 5s 87us/sample - loss: 0.2469 - accuracy: 0.9417
Epoch 10/20
60

In [82]:
results = model.evaluate(x_test, encoded_y_test,verbose=2)
results

10000/10000 - 0s - loss: 1.9082 - accuracy: 0.9412


[1.9081798430431633, 0.9412]

### STEP 6 : Prediction 

In [83]:
prediction =  model.predict_classes(x_test[30].reshape(1,28,28))


In [84]:
if prediction == 0:
  print("The data is :",x_test[i],"and I have predicted that it's a",prediction,"i.e Iris-setosa")
  print("Actual data :",x_test[i] , "actual label :",y_test[i])

elif prediction == 1:
  print("The data is :",x_test[i],"and I have predicted that it's a",prediction,"i.e Iris-versicolor")
  print("Actual data :",x_test[i] , "actual label :",y_test[i])

else:
  print("The data is :",x_test[i],"and I have predicted that it's a",prediction,"i.e Iris-virginica")
  print("Actual data :",x_test[i] , "actual label :",y_test[i])


The data is : [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0 161  31   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0 217 151   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0 133 231   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  78 231   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0 